### PR TITLE
Improvements to json generation

### PR DESCRIPTION
**Pull request by timotheeg**
Apologies for the unsolicited PR, I was a little OCD-triggered by the inconsistent indentation of the game json files 😅 . So as I was cleaning that, I figured I might as well clean the json generation as well and submit a PR for the work.

The PR *looks* large because many files are updated due to the indentation change (whitespace), and so I strongly recommend to look at the PR with the "ignore white space changes" option on (add query string `?w=1` to the changeset URL - [direct link here](https://github.com/Mazamars312/Analogue_Pocket_Neogeo/pull/42/files?w=1)), so a much better picture of the change will be visible.

In term of the generation change in the python script, I basically did the following:
1. Separate the processing from the romset definition. The game definitions are now in a single new json file named `romset.json`. The processing file itself is now very small.
2. Drop the string replacement in favour of manipulating the json structure
3. Unify the template under a single template `template.json` by mapping the data injection to memory slots.

I hope the change is understandable. Let me know if you'd like anything done differently.

Cheers!

### CODE REVIEW

**Comment by Mazamars312** [comment]
Sweet as. Ill look at this once I get my next big update up soon as this is a big one!!! So I don't want to add things while Im working on this.

**Comment by terminator2k2** [comment]
dont think this generates .json files properly for games using prom1 , other than that nice work

**Comment by timotheeg** [comment]
>  Ill look at this once I get my next big update up soon as this is a big one!!! So I don't want to add things while Im working on this.

Noted 👍 . This PR is a small thing so take a look whenever you want. I look forward to see the next update to the core. Thank you very much for contributions to the pocket! 🙏 

> dont think this generates .json files properly for games using prom1 (prom1 is missing)

Oh? Functionally it's the same the previous code. I only refactored what I could see in the main branch, and `prom1` was not in the template files, nor in any of the game json files 🤔. Could that mean some of the game files were incorrect? I don't know where the romset definition itself comes from (I only extracted it from the original python script), but is it a subset of games not using `prom1` then?

> other than that nice work

Thank you! 🙏

**Comment by terminator2k2** [comment]
i dont think maz updated the json maker, here is my maker + template 5 which was used to generate json files with prom 1

[script.zip](https://github.com/Mazamars312/Analogue_Pocket_Neogeo/files/10368779/script.zip)

**Comment by timotheeg** [comment]
Oh I see! Thanks for the file reference. I'll incorporate it to the PR tomorrow.

**Comment by terminator2k2** [comment]
i also made this one:

https://github.com/terminator2k2/Pocket-NeoGeo-Json-Maker

 which checks the rom files in the common folder and only produces the json file if the rom is present, saves having json files show up when no rom is present

**Comment by Mazamars312** [comment]
This was done by @terminator2k2 in his git hub.

**Pull request closed without merging**
