### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by thehughhefner**
Add jotego in the credits

### CODE REVIEW

**Review by retrocaster — COMMENTED** [review]
Might be worth also mentioning Jorge Cwik ([fx68k@fxatari.com], who wrote the cycle accurate 68000 that was used in this core: https://www.atari-forum.com/viewtopic.php?t=34730

**Comment by Mazamars312** [comment]
I have already added this to my todo list. When I add this and Snog's name as well for the mappers as well when I do the next release.

Most of my work was done in the main core and my own work so I want to make sure everyone is added to the credits here. 

Thanks :-)

**Comment by Mazamars312** [comment]
Thankyou as well Retrocaster Will add them too on the next build

**Comment by jotego** [comment]
Thank you

**Comment by Mazamars312** [comment]
Updated

**Pull request closed without merging**
